Feature/refactor alta material
copein-solutions/optimal-standard-ui pull request #5
Opened 2023-06-17 23:46 UTC by Fausto137

2023-06-18 22:27 UTC, manucleal requested changes

2023-06-18 22:27 UTC, manucleal commented on src/components/materialForm/MaterialForm.css
> +.prueba-borde {
Si esta clase va a quedar de forma definitiva le podemos cambiar el nombre "prueba"?

2023-06-18 22:27 UTC, manucleal commented on src/components/materialForm/MaterialForm.tsx
> +              label="Precio unitario"
Este campo debería calcularse automáticamente a medida que se va ingresando datos en los campos bajo le sección `presentación`. Ejemplo:  cantidad/precio y a la vez agregarle las unidades como sufijo tal cual explica Gonzalo en la planilla que envío para el alta material.

2023-06-18 22:27 UTC, manucleal commented on src/components/materialForm/MaterialForm.tsx
> +          {/* ------------- File upload ------------- */}
Acá falta agregar un input tipo file aunque por ahora no suba nada y luego abrimos otro feature dedicado solamente a esta funcionalidad.

2023-06-18 22:27 UTC, manucleal commented on src/components/materialForm/MaterialForm.tsx
> +          {/* ------------- Precio ------------- */}
Para redondear mas este formulario en los campos de `precio` deberíamos pasarlos a type text y validarlos con una regex para que soporte solamente este formato: 0000,00. 4 dígitos antes de la coma y solamente dos luego de la coma (o como te parezca mejor). Al menos esa es la experiencia que tuve yo con este tipo de formularios, básicamente el type number no sirve de mucho, a no ser para campos para indicar cantidades.

2023-06-19 04:28 UTC, pingold16 commented on src/components/materialForm/MaterialForm.tsx
> +          {/* ------------- Precio ------------- */}
Hay un import que se puede dar el formato de moneda que mas nos guste.

```
import CurrencyFormat from 'react-currency-formatter';

<CurrencyFormat
  value={10.99} // Valor monetario a formatear
  currency="USD" // Código de la moneda (por ejemplo, USD, EUR, etc.)
  thousandSeparator={true} // Opcional: muestra el separador de miles
  decimalScale={2} // Opcional: número de decimales a mostrar
  displayType={'text'} // Opcional: 'text' (valor formateado en texto) o 'input' (valor formateado en un input)
/>
```

2023-06-19 04:30 UTC, pingold16 commented on src/components/materialForm/MaterialForm.tsx
> +      });
Hay que agregar el resto de los parámetros

2023-06-19 13:23 UTC, Fausto137 commented on src/components/materialForm/MaterialForm.css
> +.prueba-borde {
Quedó olvidada. La borro

2023-06-21 04:02 UTC, merged